### ISSUE TITLE
Any comment breaks page layout 

### ISSUE THREAD

**Issue by defriter** [creecros/MarkdownPlus#31]
Hi! 
Version of Kanboard 1.2.38
Version of MarkdownPlus 1.1.4

When MarkdownPlus is installed any comment inside the task breaks page layout 

Example without plugin 
![IMG_20240914_045316_514](https://github.com/user-attachments/assets/4c88dcf2-3607-4b96-af10-ec0844c72c41)

Example with plugin
![IMG_20240914_045321_446](https://github.com/user-attachments/assets/fbd95a13-1ce5-48d6-87cc-37d586451267)

**Comment by Am-ilcar** [comment]
Same here

**Comment by creecros** [comment]
Try the master repo. Haven't updated the release in a while, but im pretty sure the master has addressed this.

**Comment by Am-ilcar** [comment]
Thank you very much for the answer!

I confirm that copying the master repo works fine!  
I installed it using the PluginManager plugin, but I had to make a few changes.  
First, I renamed the zip file to "MetaMagik" and also changed the name of the parent folder inside to match.  
Additionally, I had to modify the `getPluginName` function in `Plugin.php` because the namespace is "MetaMagik", but the function was returning "metaMagik", which caused an error:

**Before:**
```php
public function getPluginName()
{
    return 'metaMagik';
}
```

**After:**
```php
public function getPluginName()
{
    return 'MetaMagik';
}
```

**Comment by creecros** [comment]
I dont know why you are talking about metamagik....but ok.

**Comment by Am-ilcar** [comment]
LOL my fault, I've installed wrong plugin haha
Sorry!

**Comment by Am-ilcar** [comment]
Now it works! I downloaded the repository as a zip file and installed it manually using the 'PluginManager' plugin. Everything is working perfectly.
Thanks again!
